DOMAIN = "knvb_rinus"
NAME = "KNVB Rinus"
VERSION = "0.4.3"
BASE_URL = "https://rinus.knvb.nl"
TEAM_PATHS = ("/api/modals/get/team/profile", "/profile/team", "/profile", "/nl/profile/team")
PLAYER_PATH = "/api/modals/edit/players/open"
CALENDAR_PATHS = ("/nl/calendar", "/calendar")
CONF_COOKIE = "cookie"
DEFAULT_SCAN_INTERVAL = 900
